export class ActionType {
  // LANDING
  static REQUEST_POPULAR_SEARCH = "REQUEST_POPULAR_SEARCH";
  static REQUEST_POPULAR_SEARCH_SUCCESS = "REQUEST_POPULAR_SEARCH_SUCCESS";
  static REQUEST_POPULAR_SEARCH_FAILED = "REQUEST_POPULAR_SEARCH_FAILED";
  static REQUEST_BLOG = "REQUEST_BLOG";
  static REQUEST_BLOG_SUCCESS = "REQUEST_BLOG_SUCCESS";
  static REQUEST_BLOG_FAILED = "REQUEST_BLOG_FAILED";
  static REQUEST_AUTOCOMPLETE_SEARCH = "REQUEST_AUTOCOMPLETE_SEARCH";
  static REQUEST_AUTOCOMPLETE_SEARCH_SUCCESS =
    "REQUEST_AUTOCOMPLETE_SEARCH_SUCCESS";
  static REQUEST_AUTOCOMPLETE_SEARCH_FAILED =
    "REQUEST_AUTOCOMPLETE_SEARCH_FAILED";

  // LOGIN
  static REQUEST_LOGIN = "REQUEST_LOGIN";
  static REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS";
  static REQUEST_LOGIN_FAILED = "REQUEST_LOGIN_FAILED";

  static REQUEST_LOGIN_SOCIAL = "REQUEST_LOGIN_SOCIAL";
  static REQUEST_LOGIN_SOCIAL_SUCCESS = "REQUEST_LOGIN_SOCIAL_SUCCESS";
  static REQUEST_LOGIN_SOCIAL_FAILED = "REQUEST_LOGIN_SOCIAL_FAILED";

  // MASTER
  static REQUEST_MASTER_LOCATION = "REQUEST_MASTER_LOCATION";
  static REQUEST_MASTER_LOCATION_SUCCESS = "REQUEST_MASTER_LOCATION_SUCCESS";
  static REQUEST_MASTER_LOCATION_FAILED = "REQUEST_MASTER_LOCATION_FAILED";
  static REQUEST_MASTER_COUNTRIES = "REQUEST_MASTER_COUNTRIES";
  static REQUEST_MASTER_COUNTRIES_SUCCESS = "REQUEST_MASTER_COUNTRIES_SUCCESS";
  static REQUEST_MASTER_COUNTRIES_FAILED = "REQUEST_MASTER_COUNTRIES_FAILED";
  static REQUEST_MASTER_JOB_FUNCTION = "REQUEST_MASTER_JOB_FUNCTION";
  static REQUEST_MASTER_JOB_FUNCTION_SUCCESS =
    "REQUEST_MASTER_JOB_FUNCTION_SUCCESS";
  static REQUEST_MASTER_JOB_FUNCTION_FAILED =
    "REQUEST_MASTER_JOB_FUNCTION_FAILED";

  //HOME
  static REQUEST_BANNER = "REQUEST_BANNER";
  static REQUEST_BANNER_SUCCESS = "REQUEST_BANNER_SUCCESS";
  static REQUEST_BANNER_FAILED = "REQUEST_BANNER_FAILED";
  static REQUEST_PREFERENSI = "REQUEST_PREFERENSI";
  static REQUEST_PREFERENSI_SUCCESS = "REQUEST_PREFERENSI_SUCCESS";
  static REQUEST_PREFERENSI_FAILED = "REQUEST_PREFERENSI_FAILED";
  static REQUEST_PREFERENSI_OPPORTUNITIES = "REQUEST_PREFERENSI_OPPORTUNITIES";
  static REQUEST_PREFERENSI_OPPORTUNITIES_SUCCESS =
    "REQUEST_PREFERENSI_OPPORTUNITIES_SUCCESS";
  static REQUEST_PREFERENSI_OPPORTUNITIES_FAILED =
    "REQUEST_PREFERENSI_OPPORTUNITIES_FAILED";
  static REQUEST_REKOMENDASI_OPPORTUNITIES =
    "REQUEST_REKOMENDASI_OPPORTUNITIES";
  static REQUEST_REKOMENDASI_OPPORTUNITIES_SUCCESS =
    "REQUEST_REKOMENDASI_OPPORTUNITIES_SUCCESS";
  static REQUEST_REKOMENDASI_OPPORTUNITIES_FAILED =
    "REQUEST_REKOMENDASI_OPPORTUNITIES_FAILED";
  static REQUEST_BANNER_OPPORTUNITY = "REQUEST_BANNER_OPPORTUNITY";
  static REQUEST_BANNER_OPPORTUNITY_SUCCESS =
    "REQUEST_BANNER_OPPORTUNITY_SUCCESS";
  static REQUEST_BANNER_OPPORTUNITY_FAILED =
    "REQUEST_BANNER_OPPORTUNITY_FAILED";
  static REQUEST_CHOICE_OPPORTUNITY = "REQUEST_CHOICE_OPPORTUNITY";
  static REQUEST_CHOICE_OPPORTUNITY_SUCCESS =
    "REQUEST_CHOICE_OPPORTUNITY_SUCCESS";
  static REQUEST_CHOICE_OPPORTUNITY_FAILED =
    "REQUEST_CHOICE_OPPORTUNITY_FAILED";

  // OPPORTUNITIES
  static REQUEST_OPPORTUNITY = "REQUEST_OPPORTUNITY";
  static REQUEST_OPPORTUNITY_SUCCESS = "REQUEST_OPPORTUNITY_SUCCESS";
  static REQUEST_OPPORTUNITY_FAILED = "REQUEST_OPPORTUNITY_FAILED";

  //COMPANY DETAIL
  static REQUEST_DATA_COMPANY = "REQUEST_DATA_COMPANY";
  static REQUEST_DATA_COMPANY_SUCCESS = "REQUEST_DATA_COMPANY_SUCCESS";
  static REQUEST_DATA_COMPANY_FAILED = "REQUEST_DATA_COMPANY_FAILED";

  // STATUS LAMARAN
  static REQUEST_STATUS_LAMARAN = "REQUEST_STATUS_LAMARAN";
  static REQUEST_STATUS_LAMARAN_SUCCESS = "REQUEST_STATUS_LAMARAN_SUCCESS";
  static REQUEST_STATUS_LAMARAN_FAILED = "REQUEST_STATUS_LAMARAN_FAILED";

  //DASHBOARD
  static REQUEST_DASHBOARD_APPLICATION = "REQUEST_DASHBOARD_APPLICATION";
  static REQUEST_DASHBOARD_APPLICATION_SUCCESS =
    "REQUEST_DASHBOARD_APPLICATION_SUCCESS";
  static REQUEST_DASHBOARD_APPLICATION_FAILED =
    "REQUEST_DASHBOARD_APPLICATION_FAILED";
  static REQUEST_DASHBOARD_INTERVIEW = "REQUEST_DASHBOARD_INTERVIEW";
  static REQUEST_DASHBOARD_INTERVIEW_SUCCESS =
    "REQUEST_DASHBOARD_INTERVIEW_SUCCESS";
  static REQUEST_DASHBOARD_INTERVIEW_FAILED =
    "REQUEST_DASHBOARD_INTERVIEW_FAILED";
}
