export class DUMMY_DATA {
  static DATA_LAMARAN = [
    {
      id: 1,
      variant: "terkirim",
      label: "Terkirim",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa",
      description: "Kerjakan Sebelum 27 Okt 2021",
      location: "Jakarta Selatan",
      profileMatch: 60,
      timestamp: "2017-03-03T03:33:00.000Z",
      status: "Lamar Pribadi",
      state: "unread",
    },
    {
      id: 20,
      variant: "terkirim",
      label: "Terkirim",
      title: "Project Manager",
      company: "PT. Qerja Manfaat Bangsa",
      description: "Kerjakan Sebelum 27 Okt 2021",
      location: "Jakarta Selatan",
      profileMatch: 60,
      timestamp: "2017-03-03T03:33:00.000Z",
      status: "Lamar Pribadi",
      state: "unread",
    },
    {
      id: 21,
      variant: "terkirim",
      label: "Terkirim",
      title: "Front End Developer",
      company: "CODE.ID",
      description: "Kerjakan Sebelum 27 Okt 2021",
      location: "Jakarta Selatan",
      profileMatch: 60,
      timestamp: "2017-03-03T03:33:00.000Z",
      status: "Lamar Pribadi",
      state: "unread",
    },
    {
      id: 2,
      variant: "shortlist",
      label: "Shortlist",
      title: "wakwaw",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "Kerjakan Sebelum 27 Okt 2021",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2020-05-14T04:00:00Z",
      status: "Lamar Pribadi",
      state: "active",
    },
    //----- TLD ----------
    {
      id: 3,
      variant: "tes logika dasar",
      label: "Tes Logika Dasar",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "Kerjakan sebelum 15 Nov 2021",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2022-02-25T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "unread",
    },
    {
      id: 4,
      variant: "tes logika dasar",
      label: "Tes Logika Dasar",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "TLD Terkirim",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2022-01-25T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "terkirim",
    },
    {
      id: 5,
      variant: "tes logika dasar",
      label: "Tes Logika Dasar",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "Melewati Masa Waktu TLD",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2022-06-25T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "deadline",
    },
    //----- MCU ----------
    {
      id: 6,
      variant: "medical checkup",
      label: "Medical Checkup",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "15 Nov 2021 | 13.00-15.00 WIB",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2022-08-12T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "unread",
    },
    //----- ORVI INVITATION ----------
    {
      id: 7,
      variant: "orvi invitation",
      label: "ORVI",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "Kerjakan sebelum 15 Nov 2021",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2022-07-25T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "unread",
    },
    {
      id: 8,
      variant: "orvi invitation",
      label: "ORVI",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "ORVI terkirim",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2022-09-22T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "terkirim",
    },
    {
      id: 9,
      variant: "orvi invitation",
      label: "ORVI",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "Melewati batas waktu ORVI",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2020-01-15T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "deadline",
    },
    //----- INTERVIEW INVITATION ----------
    {
      id: 23,
      variant: "interview invitation",
      label: "Interview 1",
      title: "Quality Assurance",
      company: "PT. Qerja Manfaat Bangsa",
      description: "15 Nov 2021 | 13.00-15.00 WIB",
      location: "Jakarta Selatan",
      profileMatch: 37,
      timestamp: "2002-03-25T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "unread",
    },
    {
      id: 10,
      variant: "interview invitation",
      label: "Interview 1",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "15 Nov 2021 | 13.00-15.00 WIB",
      location: "Jakarta Selatan",
      profileMatch: 50,
      timestamp: "2002-03-25T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "unread",
    },
    {
      id: 11,
      variant: "interview invitation",
      label: "Interview 1",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "15 Nov 2021 | 13.00-15.00 WIB",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2021-10-05T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "terkirim",
    },
    {
      id: 12,
      variant: "interview invitation",
      label: "Interview 1",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "Ganti jadwal interview",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2017-12-25T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "negoisasi",
    },
    //----- GAGAL ----------
    {
      id: 13,
      variant: "gagal",
      label: "Gagal",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "15 Nov 2021 | 13.00-15.00 WIB",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2017-01-14T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "unread",
    },
    {
      id: 14,
      variant: "gagal",
      label: "Gagal",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "Mengundurkan diri",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2012-02-22T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "deadline",
    },
    //----- BERHASIL ----------
    {
      id: 15,
      variant: "berhasil",
      label: "Offering",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "15 Nov 2021 | 13.00-15.00 WIB",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2017-01-15T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "unread",
    },
    {
      id: 16,
      variant: "berhasil",
      label: "Berhasil",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "15 Nov 2021 | 13.00-15.00 WIB",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2020-10-14T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "terkirim",
    },
    {
      id: 17,
      variant: "berhasil",
      label: "Offering",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "Negoisasi Offering",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2020-10-15T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "negoisasi",
    },
    //----- LOWONGAN DITUTUP ----------
    {
      id: 18,
      variant: "lowongan ditutup",
      label: "Terkirim",
      title: "Head of Product Design System",
      company: "PT. Qerja Manfaat Bangsa ",
      description: "15 Nov 2021 | 13.00-15.00 WIB",
      location: "Jakarta Selatan",
      profileMatch: 80,
      timestamp: "2022-12-22T06:39:24+0000",
      status: "Lamar Pribadi",
      state: "active",
    },
  ];

  static DATA_NOTIFIKASI = [
    {
      id: 1,
      variant: `Job Alert (Rekomendasi)`,
      title: `Kami menemukan lowongan yang sesuai dengan profile Anda!`,
      description: `Ada banyak lowongan kerja yang sesuai dengan profile anda, klik di sini sekarang!`,
      isRead: false,
      timestamp: `2 hari lalu`,
    },
    {
      id: 2,
      variant: `Job Alert (Preferensi)`,
      title: `Lebih dari 10 Perusahaan mencari Product Manager!`,
      description: `Ada banyak lowongan kerja yang sesuai dengan profile anda, klik di sini sekarang!`,
      isRead: false,
      timestamp: `4 hari lalu`,
    },
    {
      id: 3,
      variant: `Subscribe Perusahaan`,
      title: `Lowongan Terbaru di Microsoft!`,
      description: `Microsoft baru saja mengupdate beberapa lowongan, klik di sini untuk selengkapnya.`,
      isRead: false,
      timestamp: `2 Agustus`,
    },
    {
      id: 4,
      variant: `Resume Search`,
      title: `Profil Anda diminati oleh Dribbble!`,
      description: `Selamat! Profil anda diminati oleh HRD Dribble melalui fitur Resume Search. Lihat perkembangan profil anda sekarang! `,
      isRead: true,
      timestamp: `27 Des 2021`,
    },
    {
      id: 5,
      variant: `Resume Search`,
      title: `Profil Anda diminati oleh Dribbble!`,
      description: `Profil Anda dilihat oleh Dribble melalui Resume Search. Pastikan profil anda menarik agar dipanggil HR.`,
      isRead: true,
      timestamp: `27 Des 2021`,
    },
    {
      id: 6,
      variant: `Status Lamaran`,
      title: `Gagal!`,
      description: `Mohon Maaf Maudy, Facebook memutuskan untuk tidak melanjutkan proses lamaran anda. tapi jangan khawatir karircom masih punya banyak lowongan lainnya untuk anda. klik di sini.`,
      isRead: true,
      timestamp: `10 Nov 2021`,
    },
    {
      id: 7,
      variant: `Status Lamaran`,
      title: `Hired!`,
      description: `Selamat Maudy! Anda telah diterima bekerja di Facebook. Klik di sini untuk melihat status lamaran anda di Facebook.`,
      isRead: true,
      timestamp: `10 Nov 2021`,
    },
  ];

  static DATA_LOWONGAN_TERSIMPAN = {
    lowongan: [
      {
        id: 1,
        title: "UI Designer",
        company: "PT. Tokopedia",
        salary: "Gaji Diatas Ekspetasi",
        description: "Jakarta Selatan • Full-time • Hybrid",
        profileMatch: 79,
        timestamp: "2 jam lalu",
        bookmark: true,
        prioritas: true,
      },
      {
        id: 2,
        title: "DesignOps",
        company: "PT Payfazz Teknologi Nusantara",
        salary: "Rp 10 juta - 13 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote",
        profileMatch: 100,
        timestamp: "3 jam lalu",
        bookmark: true,
        prioritas: true,
      },
      {
        id: 3,
        title: "UI/UX Designer",
        company: "Microsoft",
        salary: "Rp 9,5 juta - 15,6 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 80,
        timestamp: "5 jam lalu",
        bookmark: true,
        prioritas: false,
      },
      {
        id: 4,
        title: "UI/UX Designer",
        company: "ASTRO",
        salary: "Rp 3 juta - 6 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 85,
        timestamp: "19 jam lalu",
        bookmark: true,
        prioritas: true,
      },
      {
        id: 5,
        title: "UI/UX Designer",
        company: "Bukalapak",
        salary: "Rp 25,8 juta - 30,6 juta/bulan",
        description: "Tangerang Selatan • Fulltime • Remote ",
        profileMatch: 100,
        timestamp: "17 jam lalu",
        bookmark: true,
        prioritas: true,
      },
      {
        id: 6,
        title: "UI/UX Designer",
        company: "CoLearn",
        salary: "Rp 9,5 juta - 15,6 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 59,
        timestamp: "5 jam lalu",
        bookmark: true,
        prioritas: false,
      },
      {
        id: 7,
        title: "UI/UX Designer",
        company: "PT. Karya Anak Bangsa",
        salary: "Rp 9,5 juta - 15,6 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 59,
        timestamp: "5 jam lalu",
        bookmark: true,
        prioritas: true,
      },
      {
        id: 8,
        title: "UI/UX Designer",
        company: "Tanihub",
        salary: "Rp 9,5 juta - 15,6 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 59,
        timestamp: "5 jam lalu",
        bookmark: true,
        prioritas: false,
      },
      {
        id: 9,
        title: "UI/UX Designer",
        company: "PT. Qerja Manfaat Bangsa",
        salary: "Rp 9,5 juta - 15,6 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 90,
        timestamp: "5 jam lalu",
        bookmark: true,
        prioritas: true,
      },
      {
        id: 10,
        title: "UI/UX Designer",
        company: "PT. Karya Anak Bangsa",
        salary: "Rp 9,5 juta - 15,6 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 59,
        timestamp: "5 jam lalu",
        bookmark: true,
        prioritas: false,
      },
      {
        id: 11,
        title: "UI/UX Designer",
        company: "Tanihub",
        salary: "Rp 3 juta - 5 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 59,
        timestamp: "5 jam lalu",
        bookmark: true,
        prioritas: true,
      },
      {
        id: 12,
        title: "UI/UX Designer",
        company: "PT. Qerja Manfaat Bangsa",
        salary: "Rp 9,5 juta - 15,6 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 90,
        timestamp: "5 jam lalu",
        bookmark: true,
        prioritas: true,
      },
      {
        id: 13,
        title: "UI/UX Designer",
        company: "PT. Qerja Manfaat Bangsa",
        salary: "Rp 9,5 juta - 15,6 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 90,
        timestamp: "5 jam lalu",
        bookmark: true,
        prioritas: true,
      },
      {
        id: 14,
        title: "UI/UX Designer",
        company: "PT. Qerja Manfaat Bangsa",
        salary: "Rp 9,5 juta - 15,6 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 90,
        timestamp: "5 jam lalu",
        bookmark: true,
        prioritas: true,
      },
      {
        id: 15,
        title: "UI/UX Designer",
        company: "PT. Qerja Manfaat Bangsa",
        salary: "Rp 9,5 juta - 15,6 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 90,
        timestamp: "5 jam lalu",
        bookmark: true,
        prioritas: true,
      },
      {
        id: 16,
        title: "UI/UX Designer",
        company: "PT. Qerja Manfaat Bangsa",
        salary: "Rp 9,5 juta - 15,6 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 90,
        timestamp: "5 jam lalu",
        bookmark: true,
        prioritas: true,
      },
      {
        id: 17,
        title: "UI/UX Designer",
        company: "PT. Qerja Manfaat Bangsa",
        salary: "Rp 9,5 juta - 15,6 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 90,
        timestamp: "5 jam lalu",
        bookmark: true,
        prioritas: true,
      },
      {
        id: 18,
        title: "UI/UX Designer",
        company: "PT. Qerja Manfaat Bangsa",
        salary: "Rp 9,5 juta - 15,6 juta/bulan",
        description: "Jakarta Selatan • Fulltime • Remote ",
        profileMatch: 90,
        timestamp: "5 jam lalu",
        bookmark: true,
        prioritas: true,
      },
    ],
  };

  static DATA_PERUSAHAAN_TERSIMPAN = [
    {
      id: 1,
      company: "microsoft",
      subscribe: true,
      lowongan: [
        {
          id: 1,
          title: "UI Designer",
          company: "Microsoft",
          salary: "Rp 9,5 juta - 15,6 juta/bulan",
          description: "Jakarta Selatan • Full-time • Hybrid",
          profileMatch: 80,
          timestamp: "5 jam lalu",
          bookmark: true,
        },
        {
          id: 2,
          title: "Finance manager",
          company: "Microsoft",
          salary: "Rp 9,5 juta - 15,6 juta/bulan",
          description: "Jakarta Selatan • Full-time • Hybrid",
          profileMatch: 39,
          timestamp: "5 jam lalu",
          bookmark: false,
        },
        {
          id: 3,
          title: "UI Designer",
          company: "Microsoft",
          salary: "Rp 9,5 juta - 15,6 juta/bulan",
          description: "Jakarta Selatan • Full-time • Hybrid",
          profileMatch: 79,
          timestamp: "5 jam lalu",
          bookmark: false,
        },
        {
          id: 4,
          title: "UI Designer",
          company: "Microsoft",
          salary: "Rp 9,5 juta - 15,6 juta/bulan",
          description: "Jakarta Selatan • Full-time • Hybrid",
          profileMatch: 79,
          timestamp: "5 jam lalu",
          bookmark: false,
        },
      ],
    },
    {
      id: 2,
      company: "facebook",
      subscribe: true,
      lowongan: [
        {
          id: 1,
          title: "UI Designer",
          company: "Facebook",
          salary: "Rp 9,5 juta - 15,6 juta/bulan",
          description: "Jakarta Selatan • Full-time • Hybrid",
          profileMatch: 80,
          timestamp: "5 jam lalu",
          bookmark: true,
        },
        {
          id: 2,
          title: "Finance manager",
          company: "Facebook",
          salary: "Rp 9,5 juta - 15,6 juta/bulan",
          description: "Jakarta Selatan • Full-time • Hybrid",
          profileMatch: 39,
          timestamp: "5 jam lalu",
          bookmark: false,
        },
        {
          id: 3,
          title: "UI Designer",
          company: "Facebook",
          salary: "Rp 9,5 juta - 15,6 juta/bulan",
          description: "Jakarta Selatan • Full-time • Hybrid",
          profileMatch: 79,
          timestamp: "5 jam lalu",
          bookmark: true,
        },
        {
          id: 4,
          title: "UI Designer",
          company: "Facebook",
          salary: "Rp 9,5 juta - 15,6 juta/bulan",
          description: "Jakarta Selatan • Full-time • Hybrid",
          profileMatch: 79,
          timestamp: "5 jam lalu",
          bookmark: false,
        },
        {
          id: 5,
          title: "UI Designer",
          company: "Facebook",
          salary: "Rp 9,5 juta - 15,6 juta/bulan",
          description: "Jakarta Selatan • Full-time • Hybrid",
          profileMatch: 79,
          timestamp: "5 jam lalu",
          bookmark: false,
        },
        {
          id: 6,
          title: "UI Designer",
          company: "Facebook",
          salary: "Rp 9,5 juta - 15,6 juta/bulan",
          description: "Jakarta Selatan • Full-time • Hybrid",
          profileMatch: 79,
          timestamp: "5 jam lalu",
          bookmark: false,
        },
      ],
    },
  ];
}
